"""add_razorpay_order_id_to_orders

Revision ID: a1f71439efc4
Revises: 
Create Date: 2026-07-13 01:27:12.106133
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f71439efc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=False)
    op.add_column('reviews', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'photo_url')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_column('orders', 'razorpay_order_id')
    # ### end Alembic commands ###
